server:
  port: 9998
jwt:
  issuer: ims.kein-thema.xyz
spring:
  webflux:
    base-path: /api
  data:
    mongodb:
      host: localhost
      port: 27017
      database: infoDB
      uuid-representation: standard
      chat:
        host: ${spring.data.mongodb.host}
        port: ${spring.data.mongodb.port}
        database: serverChats
    redis:
      host: localhost
      port: 6379
minio:
  endpoint: http://127.0.0.1:9000
  access-key: gTbPiDs3xpn0Y1Y15hnz
  secret-key: I1CRcezZLZdEBbluKCtCY0VZnf4MRNcao4c88Ckm
#  bucket-name: chatBucket